=== alastria/isbe-identity-schemas-repository/commons/isbe-attestation-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ISBE Verifiable Attestation",
  "description": "Defines generic structure for any ISBE related Verifiable Credential",
  "type": "object",
  "properties": {
    "@context": {
      "description": "Semantic context for the issued credential. First element must be https://www.w3.org/ns/credentials/v2 for VC DM v2 compliance",
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      },
      "minItems": 1
    },
    "id": {
      "description": "Globally unique identifier for the issued credential",
      "type": "string",
      "format": "uri"
    },
    "type": {
      "description": "Full type chain, used to identify the credential base types",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 3,
      "allOf": [
        {
          "contains": { "const": "VerifiableCredential" },
          "minContains": 1,
          "maxContains": 1
        },
        {
          "contains": { "const": "IsbeAttestation" },
          "minContains": 1,
          "maxContains": 1
        }
      ]
    },
    "issuer": {
      "description": "DID which issued this credential",
      "type": "string",
      "format": "uri"
    },
    "validFrom": {
      "description": "Defines the date and time, when the issued credential becomes valid",
      "type": "string",
      "format": "date-time"
    },
    "validUntil": {
      "description": "Defines the date and time, when the issued credential expires",
      "type": "string",
      "format": "date-time"
    },
    "credentialSubject": {
      "anyOf": [
        {
          "$ref": "#/$defs/credentialSubject"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/credentialSubject"
          }
        }
      ]
    },
    "credentialStatus": {
      "anyOf": [
        {
          "$ref": "#/$defs/credentialStatus"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/credentialStatus"
          }
        }
      ]
    },
    "credentialSchema": {
      "anyOf": [
        {
          "$ref": "#/$defs/credentialSchema"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/credentialSchema"
          }
        }
      ]
    },
    "termsOfUse": {
      "anyOf": [
        {
          "$ref": "#/$defs/termsOfUse"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/termsOfUse"
          }
        }
      ]
    },
    "evidence": {
      "description": "Contains information about the process which resulted in the issuance of the credential",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "description": "If present, it MUST contain a URL that points to where more information about this instance of evidence can be found.",
            "type": "string"
          },
          "type": {
            "description": "Defines the evidence type extension",
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": ["type"]
      }
    },
    "proof": {
      "description": "Contains information about the proof. Within the ISBE ecosystem, credentialSubject cannot be an array.",
      "type": "object",
      "properties": {
        "type": {
          "description": "Defines the proof type",
          "type": "string"
        },
        "proofPurpose": {
          "description": "Defines the purpose of the proof",
          "type": "string"
        },
        "created": {
          "description": "Defines the date and time, when the proof has been created",
          "type": "string",
          "format": "date-time"
        },
        "verificationMethod": {
          "description": "Contains information about the verification method / proof mechanisms",
          "type": "string"
        },
        "jws": {
          "description": "Defines the proof value in JWS format",
          "type": "string"
        }
      },
      "required": [
        "type",
        "proofPurpose",
        "created",
        "verificationMethod",
        "jws"
      ]
    }
  },
  "required": [
    "@context",
    "id",
    "type",
    "issuer",
    "validFrom",
    "credentialSubject",
    "credentialSchema"
  ],
  "$defs": {
    "credentialSubject": {
      "description": "Defines information about the subject that is defined by the type chain. Within the ISBE ecosystem, credentialSubject cannot be an array.",
      "type": "object",
      "properties": {
        "id": {
          "description": "Defines the DID of the subject that is described by the issued credential",
          "type": "string"
        }
      }
    },
    "credentialStatus": {
      "description": "Defines revocation details for the issued credential. Further redefined by type extension. ",
      "type": "object",
      "properties": {
        "id": {
          "description": "Exact identity for the credential status",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "description": "Defines the revocation type extension",
          "type": "string"
        }
      },
      "required": ["id", "type"]
    },
    "credentialSchema": {
      "description": "Contains information about the credential schema on which the issued credential is based",
      "type": "object",
      "properties": {
        "id": {
          "description": "References the credential schema stored on the Trusted Schemas Registry (TSR) on which the Verifiable Authorisation is based",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "description": "Defines credential schema type",
          "type": "string",
          "enum": ["JsonSchema", "FullJsonSchemaValidator2021"]
        }
      },
      "required": ["id", "type"]
    },
    "termsOfUse": {
      "description": "Contains the terms under which the issued credential was issued",
      "type": "object",
      "properties": {
        "id": {
          "description": "Contains a URL that points to where more information about this instance of terms of use can be found.",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "description": "Defines the type extension",
          "type": "string"
        }
      },
      "required": ["type"]
    }
  }
}

=== alastria/isbe-identity-schemas-repository/use-cases/isbe/portal/lear/portalLear-example.json
{
  "@context": ["https://www.w3.org/ns/credentials/v2"],
  "id": "urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6",
  "type": [
    "VerifiableCredential",
    "IsbeAttestation",
    "IsbeDomainCredential",
    "IsbeDevDomain",
    "IsbePortalLearCredential"
  ],
  "issuer": "did:isbe:uc:0x234234234...",
  "validFrom": "2025-11-20T10:30:00Z",
  "credentialSubject": {
    "id": "did:isbe:uc:0xB87654321...",
    "mandate": {
      "id": "urn:uuid:987e6543-b21c-34d6-a789-543210fedcba",
      "mandator": {
        "organization": "GOOD AIR, S.L.",
        "organizationIdentifier": "VATFR-B12345678",
        "country": "FR",
        "commonName": "JEAN MARTIN - CNI 880692310285",
        "email": "jean.martin@goodair.fr"
      },
      "mandatee": {
        "employeeId": "A-12345678",
        "email": "jane.smith@goodair.com",
        "firstName": "Jane",
        "lastName": "Smith"
      },
      "power": [
        {
          "type": "domain",
          "domain": "DOME",
          "function": "Onboarding",
          "action": ["execute"]
        },
        {
          "type": "domain",
          "domain": "DOME",
          "function": "Onboarding",
          "action": ["execute"]
        }
      ]
    }
  },
  "credentialStatus": {
    "id": "https://status.isbe.com/credentials/status/8#492847",
    "type": "BitstringStatusListEntry",
    "statusPurpose": "message",
    "statusListIndex": "492847",
    "statusSize": 2,
    "statusListCredential": "https://status.isbe.com/credentials/status/8",
    "statusMessage": [
      { "status": "0x0", "message": "accepted" },
      { "status": "0x1", "message": "revoked" },
      { "status": "0x2", "message": "suspended" },
      { "status": "0x3", "message": "reserved" }
    ],
    "statusReference": "https://status.isbe.com/credentials/status/dictionary"
  },
  "credentialSchema": {
    "id": "https://raw.githubusercontent.com/alastria/isbe-identity-schemas-repository/refs/heads/main/use-cases/isbe/portal/lear/portalLear-schema.json",
    "type": "FullJsonSchemaValidator2021"
  },
  "termsOfUse": [
    {
      "type": "IsbeIssuanceCertificate",
      "id": "https://acreditationregistry.isbe.com/attributes/2F9A7C1B8E3D65042B1C8E3D65042F9A7C1B8E3D65042F9A7C1B8E3D6504"
    }
  ]
}
